### ISSUE TITLE
missing APIs for app and watchface : the gcolor_legible_over() function

### ISSUE THREAD

**Issue by timkrief** [pebble-dev/RebbleOS#142]
Found by trying to run my watchface and getting this warning/error message:
`[unc_symbols.h: 163] == Unimplemented: _gcolor_legible_over ==`

**Comment by timkrief** [comment]
If I wanted to implement it, in what file should I create it?

**Comment by jwise** [comment]
Maybe `rwatch/graphics/graphics.c`?
