### ISSUE TITLE
Improving emoji coverage

### ISSUE THREAD

**Issue by blakegearin** [pebble-dev/RebbleOS#161]
## Summary

Seems to be a known issue/common complaint <sub>1</sub> that many newer emojis show as empty rectangles. Is this something Rebble could address?

## Notes

- I  realize it would likely need to be dependent on new glyphs being created; I have experience with pixel art and would be willing to help on this front
- Only related issue I could find was 77 <sub>2</sub> which hasn't been merged despite being opened in June 2019

## Links
1. Reddit posts
    - https://www.reddit.com/r/pebble/comments/opj7ra/support_for_newer_emojis/
    - https://www.reddit.com/r/pebble/comments/mfpwgg/are_there_pbl_language_files_i_can_install_that/
    - https://www.reddit.com/r/pebble/comments/dw7qno/more_emojis_and_full_translation/
    - https://www.reddit.com/r/pebble/comments/609lro/new_emojis_for_pebble/
    - https://www.reddit.com/r/pebble/comments/abhny6/emoji_support/
 2. #77

**Comment by hellcp** [comment]
Have a look at https://github.com/pebble-dev/rebble-emojis/issues/4 and https://github.com/pebble-dev/rebble-emojis/issues/5. Discussion about anything in this topic should happen there I think. And feel free to contribute!
