### ISSUE TITLE
Bootsplash image

### ISSUE THREAD

**Issue by ginge** [pebble-dev/RebbleOS#18]
While RebbleOS is booting, we could throw up a nice rebble.io image

**Comment by ramonschepers** [comment]
Wondering, does this need to be generated with api commands? Or is a .png enough?

**Comment by jwise** [comment]
A beautiful .png would be great, I think.  Dovetails with #28.

**Comment by ramonschepers** [comment]
Awesome, will make one at resolution of around 256*256px with not much at the edges so it should be easy to scale/crop
