### ISSUE TITLE
Re-implement splash screen

### ISSUE THREAD

**Issue by ginge** [pebble-dev/RebbleOS#28]
The hard coded splash was removed. Re-do the boot splash:
* Create a new resource pack for the system resources, and upload. The splash should be in there in png.
* move display init to after flash init
* add hooks to load the resource from flash using the driver api
* display splash

**Comment by ramonschepers** [comment]
Regarding the term "resource pack" what does this need to contain separate from the splash image? A bit more info would be usefull :) (I happen to have made some GUI designs before, so I might help with this)

**Comment by ramonschepers** [comment]
right now the rebble.io icon is fairly monotone, which i both like and dislike, i tried to get what i had in mind onto a png without too much blingbling and such. i personally think this looks more modern :)
![r](https://user-images.githubusercontent.com/11225943/29198152-9970f1d8-7e41-11e7-815a-f35d276f9220.png)

**Comment by jneubrand** [comment]
![proposal](https://user-images.githubusercontent.com/15683245/29198751-ad9acd50-7dfb-11e7-86fc-7d5e8c6aae45.png)
Quick mockup of a platform-agnostic image using the closest matches to the rebble color scheme within the 64-color palette (turning it into b/w should be easy; I'd suggest a black background) — any center crop of this should work. Added benefit: this version could hypothetically animate to the default watchface after startup.

**Comment by Avamander** [comment]
What do you think about just subtly changing the current default boot splash's `P` in `Pebble` to `R` as in `Rebble`?

**Comment by jwise** [comment]
@avamander I think it would probably be better to more assertively be of our own design.  That is to say, it'd be better if we had something that wasn't "trying to be Pebble" (or, to the chagrin of their lawyers, "easily confusable with Pebble"...).

**Comment by Avamander** [comment]
@jwise That's going to be hard if RebbleOS runs on Pebbles, Pebble apps and like PebbleOS. Just saying "RebbleOS" would work too, my idea is that it should be minimalist as possible, no lines, no nothing.

**Comment by Stubenhocker1399** [comment]
https://github.com/ginge/FreeRTOS-Pebble/pull/55
Can be closed. 😄
