### ISSUE TITLE
Text does not re-draw correctly

### ISSUE THREAD

**Issue by TerttyCurlyfries** [pebble-dev/RebbleOS#31]
text_layer_create does not work when redrawing text when a window is reopened. For example, when systemapp is opened and launches the simple watchface, opening the systemapp fails to redraw the subtitle text on the menu.  If Windows have text layers, they will not be drawn at all on reopening. Joshua has suggested this is a ngfx render problem. 

Edit: It has also been discovered that text for a window does not display at all if two or more text_layer_create commands are issued.

**Comment by jwise** [comment]
I think this is the font cache problem, which is fixed in master
