### ISSUE TITLE
Trying to add an app in Pebble Store on Apple Phone

### ISSUE THREAD

**Issue by rachelbeam90** [pebble-dev/RebbleOS#64]
When trying to add an app (specifically "SmartWatch by Smart Monitor") to a user's iPhone, after searching for it within the Pebble Watch app store and pressing "add", users are getting the following error message in red:

cannot add app to locker

This issue is not occurring on Android phones.

**Comment by jwise** [comment]
this is not a RebbleOS bug -- try opening against pebble-dev/rebble-appstore-api (or asking in Discord #rebble-help)?

**Comment by rachelbeam90** [comment]
Hello,

thank you for your prompt response. Can you elaborate on "try opening
against pebble-dev/rebble..."

**Comment by KonradIT** [comment]
@rachelbeam90 open an issue in the repository https://github.com/pebble-dev/rebble-appstore-api
