### ISSUE TITLE
High Power Usage with Pebble 2

### ISSUE THREAD

**Issue by nicholas-itpedia** [pebble-dev/RebbleOS#68]
The battery life on a Pebble 2 with rebble v4.4.0-rbl is very poor on a Pebble 2. The Pebble 2 I have (Hardware silk21) went from 5-7 days to ~8 hours with the rebble v4.4.0-rbl software. If you search the web page at http://rebble.io/ for "battery" you will see that this is apparently a known. It is also listed here:
https://github.com/ginge/FreeRTOS-Pebble#rebbleos

I couldn't find a specific issue using "power" and "battery" search, so I created this issue. Sorry if this is a duplicate.

**Comment by WNP78** [comment]
RebbleOS is not v4.4.0-rbl, RebbleOS is an entirely new OS being developed from the ground up, and is not ready for day-to-day usage, whereas v4.4.0-rbl is simply a small change of the existing pebble OS, to fix a small bug. As to your issue, I'd think it would be a good idea to ask on the [Rebble discord](http://discord.gg/aRUAYFN).
