### ISSUE TITLE
This might be a stupid question, but: where's the source code?

### ISSUE THREAD

**Issue by brunobasto** [pebble-dev/RebbleOS#69]

**Comment by ishotjr** [comment]
@brunobasto not at all - thanks for asking! This repo is currently just for issues; source, which will eventually make its way over here one day, is presently here:

https://github.com/ginge/FreeRTOS-Pebble

:bowtie: :blue_heart:

**Comment by x29a** [comment]
Please see still pending issue #24 which states that the code is here: https://github.com/ginge/FreeRTOS-Pebble

**Comment by brunobasto** [comment]
Awesome! Thanks for getting back! I just got my pebble this week and so far the thing I like the most is how alive the community is! You guys are awesome! Makes me want to contribute.. Will try to setup my development environment and see what I can help with.
