### ISSUE TITLE
Filesystem write support

### ISSUE THREAD

**Issue by jwise** [pebble-dev/RebbleOS#71]
Some day, we'll have to write to the filesystem to persist notifications, download apps, save Bluetooth pairings, etc.  To do that, we'll need:

- [ ] Drivers for the flash
- [ ] Actual formatting routines that know how to write PBFS

**Comment by jwise** [comment]
https://github.com/pebble-dev/wiki/wiki/Filesystem-format has documentation for PBFS that I'm pretty confident about.

**Comment by ginge** [comment]
Flash drivers are beta here https://github.com/pebble-dev/RebbleOS/commit/f8e7865853b6ac8c4e8fa3d5e94fb50ea9334d7e

**Comment by jwise** [comment]
I'm calling this one done-ish!
