### ISSUE TITLE
Chalk is missing resources from chalk.json

### ISSUE THREAD

**Issue by ginge** [pebble-dev/RebbleOS#86]
Chalk is missing resource definitions from res/chalk.json

RESOURCE_ID_TO_MOON
RESOURCE_ID_REBBLE_LOGO_DARK
RESOURCE_ID_REBBLE_LOGO_LIGHT

**Comment by eliedrian** [comment]
Hi, I'd like to take this.

Is it as simple as I think it to be? Copying over from snowy.json?

**Comment by eliedrian** [comment]
Made this PR for this https://github.com/pebble-dev/RebbleOS-resources/pull/7

**Comment by AliceGrey** [comment]
Pretty sure this can be marked as resolved now. 264a389c031a5d3a5f5e568d62e59e1c347bb2c1 resolved this issue
